version: '3.7'

networks:
  default:
    external:
      name: network

services:

  pingbot:
    container_name: vsratbot
    image: vsratoslav
    restart: always
    volumes:
      - ./Pictures:/app/Pictures
